//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _07._13_2019_mvc_k30.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class K30FinanceDBEntities : DbContext
    {
        public K30FinanceDBEntities()
            : base("name=K30FinanceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<OurProjectTB> OurProjectTBs { get; set; }
        public virtual DbSet<RecentNewsTB> RecentNewsTBs { get; set; }
        public virtual DbSet<Section2Divs> Section2Divs { get; set; }
        public virtual DbSet<Section3Divs> Section3Divs { get; set; }
        public virtual DbSet<Section4Divs> Section4Divs { get; set; }
        public virtual DbSet<Section5Divs> Section5Divs { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TopSection1> TopSection1 { get; set; }
    }
}
